#卫生间门
0.8:
  glass_x: x-210 # 玻璃宽
  glass_y: y-sill-175 # 玻璃高
  border_inner_x: x-80 # 框宽
  border_inner_y: y-40 # 框高
  frame_outer_x: x-205 # 扇外框宽
  frame_outer_y: y-sill-33 # 扇外框高
  frame_inner_x: x-205 # 扇内框宽
  frame_inner_y: y-sill-33 # 扇内框高
  lock_frame: 997 # 锁(扇)
  lock_border: 1030 # 锁(框)

1.0:
  glass_x: x-205 # 玻璃宽
  glass_y: y-sill -173 # 玻璃高
  border_inner_x: x-80 # 框宽
  border_inner_y: y-40 # 框高
  frame_outer_x: x-65 # 扇外框宽
  frame_outer_y: y-sill-33 # 扇外框高
  frame_inner_x: x-225 # 扇内框宽
  frame_inner_y: y-sill-193 # 扇内框高
  lock_frame: 997 # 锁(扇)
  lock_border: 1030 # 锁(框)

1.4:
  glass_x: x-240 # 玻璃宽
  glass_y: y-sill-198 # 玻璃高
  border_inner_x: x-108 # 框宽
  border_inner_y: y-50 # 框高
  frame_outer_x: x-83 # 扇外框宽
  frame_outer_y: y-sill-42 # 扇外框高
  frame_inner_x: x-259 # 扇内框宽
  frame_inner_y: y-sill-218 # 扇内框高
  lock_frame: 997 # 锁(扇)
  lock_border: 1030 # 锁(框)
